PhotoContest.WEB/PhotoContest.WEB/Controllers/ContestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoContest.Data.UnitOfWork;
using PhotoContest.WEB.Models.BindModels;
using PhotoContest.WEB.Models.ViewModels;
using AutoMapper;
using PhotoContest.Models;

namespace PhotoContest.WEB.Controllers
{
    public class ContestController : BaseController
    {
        public ContestController(IPhotoContestData data) : base(data)
        {
        }


        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(NewContestBindModel model)
        {
            return View();
        }
    }
}

PhotoContest.WEB/PhotoContest.WEB/Controllers/HomeController.cs
namespace PhotoContest.WEB.Controllers
{
    using System.Web.Mvc;
    using PhotoContest.Data.UnitOfWork;
    using AutoMapper;
    using PhotoContest.Models;
    using Models.ViewModels;
    using System.Collections.Generic;
    public class HomeController : BaseController
    {
        public HomeController(IPhotoContestData data) : base(data)
        {
        }

        public ActionResult Index()
        {
            var contests = Data.Contests.All();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult AllUsers()
        {
            var users = Data.Users.All();

            var model = new List<UserQuickViewModel>();
            foreach (var user in users)
            {
                model.Add(Mapper.Map<User, UserQuickViewModel>(user));
            }

            return Json(model);
        }
    }
}

PhotoContest.WEB/PhotoContest.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PhotoContest.WEB/PhotoContest.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhotoContest.WEB/PhotoContest.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Photo Contest</h1>
    <p class="lead">This is a free web application for Photo Contests.</p>
    <p>@Html.ActionLink("Create new Contest", "New", "Contest", null, new { @class="btn btn-primary btn-lg" })</p>
</div>

<div class="row">
    <div><h1>Current Contests</h1></div>

    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>